site_name: Sotterranei & Dragoni
site_url: https://dnd.michaelfrancazzi.com/
theme:
  name: material
  language: it
  features:
    - navigation.tabs        # Menu a schede in alto
    - navigation.sections    # Sezioni nella sidebar
    - search.suggest         # Suggerimenti nella ricerca
    - search.highlight       # Evidenzia i risultati
  palette: 
    # Configurazione per il tema chiaro
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: brown
      accent: amber
      toggle:
        icon: material/book-open-variant
        name: Scurovisione
    # Configurazione per il tema scuro
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: brown
      accent: orange
      toggle:
        icon: material/candle
        name: Luci Danzanti
  icon:
    logo: material/sword-cross        # Un'icona con le spade incrociate invece del logo standard
    repo: fontawesome/brands/github   # Icona di GitHub
  features:
    - navigation.sections             # Organizza il menu in capitoli
    - navigation.top                  # Bottone "Torna su" a forma di freccia
    - content.code.copy               # Permette di copiare eventuali statistiche
  font:
    text: Crimson Text   # Un font con le "grazie" che ricorda i libri stampati
    code: Roboto Mono    # Per le statistiche tecniche

# Navigazione (Sidebar)
nav:
  - Il Mondo: index.md
  - Lore e Storia:
      - La Creazione: storia/origine.md
      - Grandi Regni: storia/regni.md
  - Bestiario:
      - Draghi: creature/draghi.md
      - Mostri Erranti: creature/mostri.md
  - Personaggi (NPC):
      - Alleati: npc/alleati.md
      - Nemici: npc/nemici.md
